### ISSUE TITLE
Can't play log but log is loaded

### ISSUE THREAD

**Issue by deeph46** [cleanflight/blackbox-log-viewer#26]
Hi,

I want to look my log in viewer but I can't play it in my Chrome. Sometimes shows WebGL error. I can load the log into viewer but the viewer shows me blank, the graph don't exist.
I'm using Windows 8.1 32bit, Ati Radeon Xpress 1100.

I Googled for WebGL error and give me result that is from VGA driver. I have updated it but still no luck. Any how to fix this?

Thanks

**Comment by thenickdude** [comment]
When you use the Cleanflight Configurator, does the 3D model of the craft on the main page show as a simple box (rather than a quadcopter model with propellers and everything)? If so, your graphics card or graphics card drivers don't support the WebGL that the log viewer currently uses for its 3D craft model. In this case I can fix the log viewer to use a 2D craft model instead.

**Comment by deeph46** [comment]
In the Cleanflight Configurator the 3D model show as a quadcopter model. Then if using 2D craft model, does it work like 3D craft model (like the motors movement)?.

**Comment by thenickdude** [comment]
Interesting, in that case your graphics card does support WebGL. Can you email me your log file? n.sherlock@gmail.com

**Comment by deeph46** [comment]
Sent.

**Comment by deeph46** [comment]
Sorry, just noticed that in the Cleanflight Configurator the 3D model is in box mode.

**Comment by thenickdude** [comment]
Ah okay, in that case your computer doesn't support the 3D model. I've now added a fallback mode to the log viewer which will draw the craft in 2D on your computer instead, please update to the latest version:

https://chrome.google.com/webstore/detail/cleanflight-blackbox-expl/cahpidddaimdojnddnahjpnefajpheep
