### ISSUE TITLE
Exporting video always Calculating

### ISSUE THREAD

**Issue by apeelme** [cleanflight/blackbox-log-viewer#49]
I tried on Debian Jessie Mate, Ubuntu Mate 16.04 (now fresh install) & Chrome 53.0.2785.116 (64-bit) at all times and nothing happens, always Calculating... the file size, and no rendering.

Here is the DeveloperTools console output:
http://imgur.com/a/eypT0

**Comment by thenickdude** [comment]
This is a bug in Betaflight's branch of the log viewer which has already
been fixed in Cleanflight's version (the one in this repository). Please
use their bug tracker to report it to them.

Cheers,
Nick

**Comment by apeelme** [comment]
I installed from the Chrome WebStore (CF & BF BlackboxExplorer) and both have this problem. Here's the CF console: http://imgur.com/a/sT6lb

**Comment by apeelme** [comment]
Download this repo...load index.html, open log file, export video...same error. :(

**Comment by thenickdude** [comment]
Ah okay this is apparently a WebP encoding quirk specific to Chrome 53, because it doesn't seem to happen any longer on Chrome 54. It should now be worked around in the newest version, 0.1.6.4. You can update to this version manually by ticking the "developer mode" tickbox on Chrome's extensions settings page, then clicking the "Update extensions now" button.
