### ISSUE TITLE
Add ability to render and export video

### ISSUE THREAD

**Issue by Mauronic** [cleanflight/blackbox-log-viewer#7]
Title says it all. Would be a killer feature!

**Comment by joshuabardwell** [comment]
Seconded. Currently, I use a screencast app to record playback, but this isn't ideal for any number of reasons.

IIRC, @thenickdude previously said that the main issue is ability to render video from Java.

**Comment by thenickdude** [comment]
Yeah JavaScript doesn't really have a video encoder available. The closest thing I've found is the [Whammy WebM encoder](https://github.com/antimatter15/whammy), which is a hack that only works on Chrome. This would need significant reworking in order to make it suitable for blackbox video rendering.

**Comment by fedorcomander** [comment]
Can we use host application via messaging? Yes, its in chrome only.

**Comment by fedorcomander** [comment]
Another option would be generate ffmpeg script for the video file, log index, dimensions, log start...

**Comment by joshuabardwell** [comment]
The idea I had was that possibly the features from the viewer could be cross-ported to the renderer, then the viewer could be set up to export a config file that could be read by the renderer, which would then generate the PNG overlays from the data. That way you could use the awesome UI of the viewer to set up your traces instead of cumbersome command line options.

It would be great if the viewer and renderer could be coded so as to easily share feature sets, but given that the renderer was not developed in JS and the viewer is, I suspect this would be challenging.

**Comment by fedorcomander** [comment]
While ago i made script to render from command line, if you interested.

See video description https://www.youtube.com/watch?v=bBzVdYO5u04

May be you can use it for a while / change it a bit for your needs.

**Comment by joshuabardwell** [comment]
@fedorcomander this is fine, but AFAIK, BB render doesn't support the customizable graphs that BB viewer does.

This is a good script for combining the overlay without having to use a full video editor, though.
